markdown: kramdown
highlighter: coderay
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
    coderay_css: class
#permalink: /:year-:month-:day/:title.html
safe: true
lsi: false
exclude: [CNAME, .git]