version: '2'
services:
  api:
    build: .
    volumes:
      - .:/opt/application
    ports:
     - "5000:3000"
    environment:
      - HOME_DIR=/opt/application
      - NODE_ENV=development
      - NODE_PATH=/opt/application/lib
      - NODE_CONFIG_DISABLE_FILE_WATCH=Y
      - NODE_LOGGER_LEVEL=info
      - NODE_LOGGER_GRANULARLEVELS=1
      - NODE_LOGGER_PLUGIN=util
      - NODE_CONFIG_DIR=/opt/application/config
      - NODE_LOG_DIR=/opt/application/logs
      - NODE_HOT_RELOAD=1
      - NODE_CLUSTERED=0
    command: [npm, run, docker-dev-start]
